<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Mappings\AutoMapperProfile\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.2.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.8" />
    <PackageReference Include="Moq" Version="4.18.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HotelBilling.Domain\HotelBilling.Domain.csproj" />
    <ProjectReference Include="..\HotelBilling.Shared\HotelBilling.Shared.csproj" />
  </ItemGroup>

</Project>
