using FluentValidation;
using HotelBilling.Application.DTOs.Booking;
using System;

namespace HotelBilling.Application.Validators
{
    public class BookingCreateDtoValidator : AbstractValidator<BookingCreateDto>
    {
        public BookingCreateDtoValidator()
        {
            // Guest
            RuleFor(x => x.GuestName).NotEmpty();
            RuleFor(x => x.Email).NotEmpty().EmailAddress();
            RuleFor(x => x.PhoneNumber).NotEmpty().MinimumLength(6);

            // Booking
            // BookingNumber is generated by the service when not provided by the UI
            // Remove required validation to allow server-side generation
            RuleFor(x => x.CheckInDate).LessThan(x => x.CheckOutDate).WithMessage("Check-in must be before check-out");
            RuleFor(x => x.CheckOutDate).GreaterThan(x => x.CheckInDate).WithMessage("Check-out must be after check-in");
            RuleFor(x => x.Adults).GreaterThanOrEqualTo(1);

            // Room
            RuleFor(x => x.RoomId).GreaterThan(0);

            // ID proof
            When(x => x.IdProofType != null, () =>
            {
                RuleFor(x => x.IdProofNumber).NotEmpty().WithMessage("ID proof number is required when ID proof type is selected");
            });
        }
    }
}
